pipeline:
  name: cicd
  identifier: cicd
  projectIdentifier: harnesscicdnodejs
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github1
        repoName: harness-ci-example.git
        build: <+input>
  stages:
    - stage:
        name: BUILD
        identifier: BUILD
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: npm test
                  identifier: npm_test
                  spec:
                    shell: Sh
                    command: npm test
              - step:
                  type: Run
                  name: docker build and push
                  identifier: docker_build_and_push
                  spec:
                    shell: Sh
                    command: |-
                      docker build -t veluprabhakaranv/helloworld-nodejs:latest .
                      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io
                      docker push veluprabhakaranv/helloworld-nodejs:latest
                    envVariables:
                      DOCKER_USERNAME: veluprabhakaranv
                      DOCKER_PASSWORD: Prince@1110
